language: minimal
git:
  depth: 1

os:
  - linux

before_install:
  - wget https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/201901172323/squeak.cog.spur_linux64x64_201901172323.tar.gz
  - tar -xvzf squeak.cog.spur_linux64x64_201901172323.tar.gz
  - echo ./sqcogspur64linuxht/bin/squeak --version

script:
  - ./runTests.sh

before_deploy:
  - ./generateRelease.sh
  # Set up git user name and tag this commit
  - git config --local user.name cuis_dev
  - git config --local user.email mailman@cuis-smalltalk.org
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "cuis-linux-x64.tar.gz"
  skip_cleanup: true


