language: minimal

git:
  depth: 1

arch:
  - amd64
  - arm64

os:
  - linux
  - osx

before_install:
  - .ContinuousIntegrationScripts/installVm.sh
  - .ContinuousIntegrationScripts/installUpdates.sh

script:
  - .ContinuousIntegrationScripts/runTests.sh
