language: bash

git:
  depth: 1

os:
  - linux
  - osx
  - windows

filter_secrets: false

before_install:
  - .ContinuousIntegrationScripts/installVm.sh
  - .ContinuousIntegrationScripts/installUpdates.sh

script:
  - .ContinuousIntegrationScripts/runTests.sh
