language: minimal
git:
  depth: 1

os:
  - linux

before_install:
  - wget https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/201901172323/squeak.cog.spur_linux64x64_201901172323.tar.gz
  - tar -xvzf squeak.cog.spur_linux64x64_201901172323.tar.gz
  - echo ./sqcogspur64linuxht/bin/squeak --version

script:
  - IMAGE_FILE="$(ls | grep 'Cuis5.0-[0-9]\+.image')"
  - CHANGES_FILE="$(ls | grep 'Cuis5.0-[0-9]\+.changes')"
  - mkdir release
  - cp "$IMAGE_FILE" cuis.image
  - ./sqcogspur64linuxht/bin/squeak -vm-display-null cuis.image -s runTests.st
  - cp -r sqcogspur64linuxht release/vm
  - cp -r Packages release
  - cp CuisV5.sources "$IMAGE_FILE" "$CHANGES_FILE"  release
  - tar -czvf cuis-linux-x64.tar.gz release

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name cuis_dev
  - git config --local user.email mailman@cuis-smalltalk.org
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "cuis-linux-x64.tar.gz"
  skip_cleanup: true


