language: minimal
git:
  depth: 1

os:
  - linux

before_install:
  - wget https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/201901172323/squeak.cog.spur_linux64x64_201901172323.tar.gz
  - tar -xvzf squeak.cog.spur_linux64x64_201901172323.tar.gz
  - echo ./sqcogspur64linuxht/bin/squeak --version

script:
- |
  ./sqcogspur64linuxht/bin/squeak  \
  -vm-display-null \
  $(ls | grep 'Cuis5.0-[0-9]\+.image') \
  -s runTests.st
