language: minimal

git:
  depth: 1

os:
  - linux

before_install:
  - wget https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/201901172323/squeak.cog.spur_linux64x64_201901172323.tar.gz
  - tar -xvzf squeak.cog.spur_linux64x64_201901172323.tar.gz
  - sqcogspur64linuxht/bin/squeak --version

script:
  - .ContinuousIntegrationScripts/installUpdates.sh
  - .ContinuousIntegrationScripts/runTests.sh
