'From Cuis7.7 [latest update: #7929] on 13 May 2026 at 10:52:18 am'!
!methodRemoval: ClassChangeRecord #noteNewMethod:selector:priorMethod: stamp: 'jmv 13/May/2026 10:49:20'!
ClassChangeRecord removeSelector: #noteNewMethod:selector:priorMethod:!
!methodRemoval: ChangeSet class #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor: stamp: 'jmv 13/May/2026 10:48:59'!
ChangeSet class removeSelector: #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor:!
!methodRemoval: ChangeSet class #methodChangedFrom:to:selector:inClass:requestor: stamp: 'jmv 13/May/2026 10:49:09'!
ChangeSet class removeSelector: #methodChangedFrom:to:selector:inClass:requestor:!
!methodRemoval: ChangeSet #noteNewMethod:forClass:selector:priorMethod: stamp: 'jmv 13/May/2026 10:49:15'!
ChangeSet removeSelector: #noteNewMethod:forClass:selector:priorMethod:!
!methodRemoval: SmalltalkCompleter class #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor: stamp: 'jmv 13/May/2026 10:49:00'!
SmalltalkCompleter class removeSelector: #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor:!
!methodRemoval: SystemChangeNotifier #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor: stamp: 'jmv 13/May/2026 10:48:59'!
SystemChangeNotifier removeSelector: #methodAdded:selector:inProtocol:class:methodTimeStamp:requestor:!
!methodRemoval: SystemChangeNotifier #methodChangedFrom:to:selector:inClass:requestor: stamp: 'jmv 13/May/2026 10:49:08'!
SystemChangeNotifier removeSelector: #methodChangedFrom:to:selector:inClass:requestor:!
