Extension { #name : 'SmallFloat64' }

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestAdd: aNumber [
	"Primitive. Answer the sum of the receiver and aNumber. Essential.
	Fail if the argument is not a Float. See Object documentation
	whatIsAPrimitive."

	<primitive: 541>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestArcTan [

	<primitive: 557>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestDivideBy: aNumber [
	"Primitive. Answer the result of dividing receiver by aNumber.
	Fail if the argument is not a Float.
	Essential. See Object clas >> whatIsAPrimitive."

	<primitive: 550>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestEqual: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is equal to the argument. Otherwise return false.
	Fail if the argument is not a Float. Essential. See Object documentation
	whatIsAPrimitive."

	<primitive: 547>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestExp [
	"Primitive. Answer the sum of the receiver and aNumber. Essential.
	Fail if the argument is not a Float. See Object documentation
	whatIsAPrimitive."

	<primitive: 559>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestExponent [
	"Primitive. Answer the sum of the receiver and aNumber. Essential.
	Fail if the argument is not a Float. See Object documentation
	whatIsAPrimitive."

	<primitive: 553>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestGreater: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is greater than the argument. Otherwise return false.
	Fail if the argument is not a Float. Essential. See Object documentation
	whatIsAPrimitive."

	<primitive: 544>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestGreaterEqual: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is greater than or equal to the argument. Otherwise return
	false. Fail if the argument is not a Float. Optional. See Object documentation 
	whatIsAPrimitive. "

	<primitive: 546>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestLess: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is less than the argument. Otherwise return false.
	Fail if the argument is not a Float. Essential. See Object documentation
	whatIsAPrimitive."

	<primitive: 543>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestLessEqual: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is less than or equal to the argument. Otherwise return
	false. Fail if the argument is not a Float. Optional. See Object
	documentation whatIsAPrimitive."

	<primitive: 545>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestLn [
	"Primitive. Answer the sum of the receiver and aNumber. Essential.
	Fail if the argument is not a Float. See Object documentation
	whatIsAPrimitive."

	<primitive: 558>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestMultiplyBy: aNumber [
	"Primitive. Answer the result of multiplying the receiver by aNumber.
	Fail if the argument is not a Float. Essential. See Object documentation
	whatIsAPrimitive."

	<primitive: 549>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestNotEqual: aNumber  [
	"Primitive. Compare the receiver with the argument and return true
	if the receiver is not equal to the argument. Otherwise return false.
	Fail if the argument is not a Float. Optional. See Object documentation
	whatIsAPrimitive."

	<primitive: 548>
	^#fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestSin [
	<primitive: 556>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestSqrt [
	<primitive: 555>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestSubtract: aNumber [
	"Primitive. Answer the difference between the receiver and aNumber.
	Fail if the argument is not a Float. Essential. See Object documentation
	whatIsAPrimitive."

	<primitive: 542>
	^ #fail
]

{ #category : '*BaseImageTests-Kernel-Numbers' }
SmallFloat64 >> primTestTruncated [
	<primitive: 551>
	^ #fail
]
