Class {
	#name : 'NoclashABCclasVarZZ_DclExample06',
	#superclass : 'Object',
	#instVars : [
		'a',
		'b',
		'c'
	],
	#classVars : [
		'ZZ'
	],
	#category : 'TestDynamicCuisLibraries-SubjectClasses06',
	#package : 'TestDynamicCuisLibraries',
	#tag : 'SubjectClasses06'
}

{ #category : 'other' }
NoclashABCclasVarZZ_DclExample06 class >> setAndAnswerZZ2 [
	ZZ := 12742.
	^ZZ
]

{ #category : 'other' }
NoclashABCclasVarZZ_DclExample06 >> setAndAnswerZZ [
	ZZ := 1274.
	^ZZ
]
