name: Run tests
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          run: ulimit -n 99 && ulimit -Hn 99

    steps:
      - uses: actions/checkout@v2
      - run: .ContinuousIntegrationScripts/installVm.sh
      - run: .ContinuousIntegrationScripts/installUpdates.sh
      - run: .ContinuousIntegrationScripts/runTests.sh
